### ISSUE TITLE
What does this module do?

### ISSUE THREAD

**Issue by blv-brunoneyra** [joke/zim-starship#37]
Can't really tell from reading the script.
It doesn't seem to run `eval "$(starship init zsh)"` as I expected.

**Comment by joke** [comment]
@blv-brunoneyra
- it extracts the init code.
-  zcompiles it for faster startup time.
- repeates the progress if a newer starship version is detected
- extracts the zsh complete

**Comment by blv-brunoneyra** [comment]
amazing.
it seems like [these lines](https://github.com/joke/zim-starship/blob/main/init.zsh#L9-L10) are outputting `starship init zsh` into a file then compiling it.
on second inspection, following your comment, it made a lot more sense.
thanks!
